### ISSUE TITLE
Add some empty files

### ISSUE THREAD

**Issue by rubenbanuelos** [rubenbanuelos/toyingWithGithub#1]
Let's begin with simple stuff add these files to a new branch from devel called empty-files (Hint: use `touch` to make it faster)

- [x] readme.txt
- [x] project/todo.txt
- [x] newfolder/stuff.txt

When the checklist is done, merge empty-files into devel branch.

**Comment by said3427** [comment]
Empecé con esta parte. La regué en poner "Devel" en lugar de "devel"

**Comment by said3427** [comment]
Ya la  borré!
